nova-omnia/lernello

- frontend/src/app.css
- frontend/src/lib/models/kit.ts
- frontend/src/routes/(app)/+layout.svelte
- frontend/src/routes/(app)/dashboard/+page.svelte
- frontend/src/routes/(app)/learningkit/create-form/+page.server.ts
- frontend/src/routes/(app)/learningkit/create-form/+page.svelte
- frontend/src/routes/change-password/+page.svelte
- frontend/src/routes/login/+page.svelte
@julianmaag I saw you didnt use proper skeletonui/tw form components yet and were not in sync w/ the ui prototype so I cleaned it up a little
> Tidy up lk create form

- backend/src/main/java/ch/nova_omnia/lernello/service/CustomUserDetailsService.java
- frontend/src/lib/api/collections/user.ts
followup to fix auth flow, I introduced some bugs for change pw flow
> fix broken change password auth flow

- frontend/src/lib/api/collections/file.ts
- frontend/src/lib/components/FileUpload.svelte
- frontend/src/lib/components/dialogs/AddTraineeModal.svelte
- frontend/src/lib/components/displays/FileDisplay.svelte
- frontend/src/lib/i18n/locales/en.json
- frontend/src/routes/(app)/learningkit/[learningKitId]/+page.svelte
> _implemented remove selected files, added upload new file button_
---
> _when not using files? gives warning because MulitpartFile Schema not fully implemented yet_
> 240 incooperate addnewfile in mulltiselector

- frontend/src/routes/(app)/learningunit/create-form/+page.svelte
[refactor: invalidate learningkit after LU creation](https://github.com/nova-omnia/lernello/commit/0ccf6036d6f233f0ba871940df97673dcfae46ca)
> refactor: invalidate learningkit after LU creation

- frontend/src/routes/login/+page.server.ts
- frontend/src/routes/login/+page.svelte
Switched to [SuperForms Events](https://superforms.rocks/concepts/events) instead of `$effect` and also switched to `redirect` in load function coupled with [invalidateAll: false](https://superforms.rocks/concepts/enhance) for the form so the server can already redirect
> refactor: leverage superforms for login form submission

- frontend/src/lib/components/Topbar.svelte
> useless url page path in topbar removed
---
> refactor: remove page.url from topbar

- frontend/src/routes/login/+page.svelte
Fixes userInfo outdated on first login - invalidate
- checked my changes
- pr is small enoug for review
> Fix-login-language

- backend/src/main/java/ch/nova_omnia/lernello/api/block/AIBlockRestController.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/block/create/AIGeneratedMultipleChoiceRequest.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/block/create/AIGeneratedQuestionBlockRequest.java
- backend/src/main/java/ch/nova_omnia/lernello/service/AIBlockService.java
- backend/src/main/java/ch/nova_omnia/lernello/service/ai/AIClient.java
> _implemented be ai question generation._
---
> feat: add question block generation functionality

- backend/src/main/java/ch/nova_omnia/lernello/LoadDatabase.java
- backend/src/main/java/ch/nova_omnia/lernello/service/file/FileSystemService.java
- bruno/main_collection/File/Upload File.bru
> _allow duplicated file upload ._
---
> _when adding file, the multiselect for files doesn't update immediatley (only when reloading browser)_
> allow filename duplicates and add counter of file

- .idea/misc.xml
- backend/src/main/java/ch/nova_omnia/lernello/api/LearningKitRestController.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/LearningKit.java
- backend/src/main/java/ch/nova_omnia/lernello/repository/LearningKitRepository.java
- backend/src/main/java/ch/nova_omnia/lernello/repository/UserRepository.java
- backend/src/main/java/ch/nova_omnia/lernello/service/LearningKitService.java
- frontend/src/lib/api/collections/learningKit.ts
- frontend/src/lib/components/FileUpload.svelte
- frontend/src/lib/components/GenerateTheoryModal.svelte
- frontend/src/lib/components/dialogs/ConfirmDialog.svelte
- frontend/src/lib/components/dialogs/CreateMultipleChoiceModal.svelte
- frontend/src/lib/components/learningkit/LearningKitItem.svelte
- frontend/src/lib/components/learningkit/LearningKitTabs.svelte
- frontend/src/lib/i18n/locales/en.json
- frontend/src/routes/(app)/dashboard/+page.svelte
- frontend/src/routes/(app)/learningkit/[learningKitId]/+page.server.ts
- frontend/src/routes/(app)/learningkit/[learningKitId]/+page.svelte
- frontend/src/routes/(app)/learningkit/[learningKitId]/create-trainee/+page.server.ts
- frontend/src/routes/(app)/learningkit/[learningKitId]/create-trainee/+page.svelte
- frontend/src/routes/(app)/learningkit/[learningKitId]/edit-form/+page.svelte
- frontend/src/routes/(app)/learningkits/+page.svelte
- frontend/src/routes/(app)/learningunit/create-form/+page.server.ts
- frontend/src/routes/(app)/learningunit/create-form/+page.svelte
> 309 bugfixes learning kit

- frontend/src/lib/components/FileUpload.svelte
> refactor: remove upload pending indicator from FileUpload component

- backend/src/main/java/ch/nova_omnia/lernello/api/block/AIBlockRestController.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/block/ai/AIGeneratedQuestionBlockRequest.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/block/ai/AIGeneratedTheoryBlockRequest.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/block/TheoryBlockResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/service/AIBlockService.java
- frontend/src/lib/api/collections/aiBlock.ts
- frontend/src/lib/components/GenerateTheoryModal.svelte
- frontend/src/lib/components/LearningUnitTrainer.svelte
- frontend/src/lib/components/blocks/BlockAiGenerationButton.svelte
- frontend/src/lib/components/blocks/BlockEditor.svelte
- frontend/src/lib/components/blocks/BlockIconHeader.svelte
- frontend/src/lib/components/blocks/BlockItem.svelte
- frontend/src/lib/components/blocks/BlockMultipleChoiceItem.svelte
- frontend/src/lib/components/blocks/BlockQuestionItem.svelte
- frontend/src/lib/components/blocks/BlockTheoryItem.svelte
- frontend/src/lib/components/dialogs/CreateMultipleChoiceModal.svelte
- frontend/src/lib/schemas/request/block/GenerateAITheoryBlock.ts
- frontend/src/lib/schemas/request/block/GeneratedAIQuestionBlock.ts
- frontend/src/lib/schemas/response/BlockRes.ts
- frontend/src/lib/utils/createDebounced.ts
- frontend/src/routes/(app)/learningunit/[learningUnitId]/training/+page.svelte
- Moves the responsibility of setting block contents back to the FE instead of the BE
- Debounced block updates
- Loading Modal State (disabled buttons)
- Fixes flicker issues of adding blocks
> Cleanup ai generation

- frontend/src/lib/components/learningkit/LearningKitTabs.svelte
- frontend/src/lib/components/learningkit/displays/LearningUnitItem.svelte
- frontend/src/lib/components/learningkit/tab/FilesTab.svelte
- frontend/src/lib/components/learningkit/tab/LearningUnitsTab.svelte
- frontend/src/routes/(app)/learningkit/[learningKitId]/+page.server.ts
- frontend/src/routes/(app)/learningkit/[learningKitId]/+page.svelte
> Logging in as a Trainee should only show the LearningUnits
---
>
> feat: added role to LearningKitView

- frontend/.env.example
-made a short explanation on how to use .env in .env.example
-added AI-API-KEY to .env.example
---
> fix:Update example .env file with correct API base URL and instructions

- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/CheckMultipleChoiceAnswerDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/CheckQuestionAnswerDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/LearningKitOpened.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/LearningUnitOpenedDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/LearningKitProgressResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/LearningUnitProgressDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/MultipleChoiceAnswerValidationResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/QuestionAnswerValidationResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/mapper/ProgressMapper.java
- backend/src/main/java/ch/nova_omnia/lernello/repository/BlockProgressRepository.java
- backend/src/main/java/ch/nova_omnia/lernello/repository/LearningKitProgressRepository.java
- backend/src/main/java/ch/nova_omnia/lernello/repository/LearningUnitProgressRepository.java
- backend/src/main/java/ch/nova_omnia/lernello/service/CustomUserDetailsService.java
> DTOs, Scopes, Mapper and Repos
---
>  Services and RestController but it's in another branch already implemented
> feat: 273 pr breakdown - DTOs, Mapper, Scopes and Repos

- backend/src/main/java/ch/nova_omnia/lernello/model/data/block/scorable/ScorableBlock.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/LearningKitProgress.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/LearningUnitProgress.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/block/BlockProgress.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/block/TheoryBlockProgress.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/block/scorable/MultipleChoiceBlockProgress.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/block/scorable/QuestionBlockProgress.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/block/scorable/ScorableBlockProgress.java
> introduction of scorable blocks
---
> feat: 273 pr breakdown - introduction of scorable blocks

- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/CheckMultipleChoiceAnswerDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/CheckQuestionAnswerDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/LearningKitOpened.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/LearningUnitOpenedDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/LearningKitProgressResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/LearningUnitProgressDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/MultipleChoiceAnswerValidationResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/QuestionAnswerValidationResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/block/scorable/MultipleChoiceBlockProgress.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/block/scorable/QuestionBlockProgress.java
> after testing it out with bru, it didn't work, so i bugfixed it.
---
>
> feat: bugfix 273

- frontend/src/lib/api/collections/progress.ts
- frontend/src/lib/schemas/request/progress/CheckMultipleChoiceAnswerSchema.ts
- frontend/src/lib/schemas/request/progress/CheckQuestionAnswerSchema.ts
- frontend/src/lib/schemas/request/progress/LearningKitOpenedSchema.ts
- frontend/src/lib/schemas/request/progress/LearningUnitOpenedSchema.ts
- frontend/src/lib/schemas/response/progress/LearningKitProgressResSchema.ts
- frontend/src/lib/schemas/response/progress/LearningUnitProgressResSchema.ts
- frontend/src/lib/schemas/response/progress/MultipleChoiceAnswerValidationResSchema.ts
- frontend/src/lib/schemas/response/progress/QuestionAnswerValidationResSchema.ts
> added schemas and collection for progress
---
> implementation of the collections
> 272 progress schemas and collections

- backend/src/main/java/ch/nova_omnia/lernello/config/JpaAuditingConfig.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/LearningKitProgressResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/LearningUnitProgressDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/LearningKitProgress.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/LearningUnitProgress.java
- backend/src/main/java/ch/nova_omnia/lernello/service/ProgressService.java
> Replaced LocalDateTime to ZoneDateTime,
---
> feat: bugfix progress time

- backend/src/main/java/ch/nova_omnia/lernello/api/ProgressRestController.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/TheoryBlockViewedDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/TheoryBlockViewedResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/mapper/ProgressMapper.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/progress/block/TheoryBlockProgress.java
- backend/src/main/java/ch/nova_omnia/lernello/repository/BlockProgressRepository.java
- backend/src/main/java/ch/nova_omnia/lernello/service/ProgressService.java
- frontend/src/lib/api/collections/progress.ts
- frontend/src/lib/components/blocks/BlockTheoryItem.svelte
- frontend/src/lib/schemas/request/progress/TheoryBlockViewedSchema.ts
- frontend/src/lib/schemas/response/progress/TheoryBlockViewedResSchema.ts
> The TheoryBlockProgress wasn't generated until now.
---
> -
---
> feat: theoryblockprogress implementation

- backend/src/main/java/ch/nova_omnia/lernello/LoadDatabase.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/LearningUnit.java
- backend/src/main/java/ch/nova_omnia/lernello/repository/BlockProgressRepository.java
- backend/src/main/java/ch/nova_omnia/lernello/repository/LearningUnitProgressRepository.java
- backend/src/main/java/ch/nova_omnia/lernello/service/LearningUnitService.java
- frontend/src/lib/components/blocks/BlockSelectPopover.svelte
> Fixes two major bugs. The reorder bug and another bug which prevented deleting blocks, if a blockprogress to it has been created.
---
> \-
> 314 block reorder bug

- frontend/src/lib/components/learningkit/LearningKitItem.svelte
- frontend/src/lib/components/learningkit/displays/LearningUnitItem.svelte
- frontend/src/routes/(app)/+layout.svelte
> Implementation of Progressbar in Learningkititem and LearningUnitItem
Uncompleted and Completed Learningunits
CompletedLearningkit
Uncompleted Learningkit
---
> \-
> feat: implementation progressbar

- backend/src/main/java/ch/nova_omnia/lernello/api/ProgressRestController.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/LearningKitProgressResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/mapper/ProgressMapper.java
- backend/src/main/java/ch/nova_omnia/lernello/service/ProgressService.java
> further update of progress
---
> \-
> feat: progress update backend

- backend/src/main/java/ch/nova_omnia/lernello/config/ProbeResourceHttpRequestHandler.java
- frontend/src/lib/components/FileUpload.svelte
> 378 bug opening jpeg

- frontend/src/lib/components/learningkit/LearningKitItem.svelte
- frontend/src/lib/components/learningkit/displays/PublishedStatusIndicator.svelte
- frontend/src/lib/i18n/locales/en.json
- frontend/src/routes/(app)/dashboard/+page.svelte
- frontend/src/routes/(app)/learningkit/[learningKitId]/+page.svelte
- frontend/src/routes/(app)/learningkits/+page.svelte
> In the Dashboard and in the Learningkit view, there is a new component, which shows if a learningkit has been published or not.
---
> \-
> feat: publisehd indicator implementation

- backend/src/main/java/ch/nova_omnia/lernello/model/data/block/TheoryBlock.java
- frontend/src/lib/components/blocks/BlockSelectPopover.svelte
- frontend/src/lib/schemas/request/block/CreateBlock.ts
- frontend/src/lib/states/blockActionState.svelte.ts
> in the text editor ctrl + a + delete now works
---
> _
> fix: remove blank constraint

- frontend/src/routes/(app)/+layout.svelte
> fix: correct user role reference in Sidebar component

- frontend/src/lib/components/blocks/BlockTheoryItem.svelte
> fix: adjust IntersectionObserver threshold for BlockTheoryItem component

- backend/build.gradle.kts
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/CheckMultipleChoiceAnswerDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/LearningKitOpened.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/request/progress/LearningUnitOpenedDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/progress/MultipleChoiceAnswerValidationResDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/dto/response/user/LoggedInUserDTO.java
- backend/src/main/java/ch/nova_omnia/lernello/model/data/block/TheoryBlock.java
- backend/src/main/java/ch/nova_omnia/lernello/security/AuthTokenFilter.java
- frontend/src/lib/components/learningkit/displays/LearningUnitItem.svelte
> Refactor made renamable label of learning unit visible with hover

- backend/src/main/java/ch/nova_omnia/lernello/mapper/block/BlockMapper.java
- backend/src/main/java/ch/nova_omnia/lernello/service/block/AIBlockService.java
- frontend/src/lib/components/FileUpload.svelte
- frontend/src/lib/components/blocks/BlockIcon.svelte
- frontend/src/lib/components/blocks/BlockIconHeader.svelte
- frontend/src/lib/components/blocks/BlockSelectPopover.svelte
- frontend/src/lib/components/statistics/LearningKitStatisticCard.svelte
- frontend/src/lib/components/statistics/LearningKitStatisticsOverview.svelte
- frontend/src/routes/(app)/dashboard/+page.svelte
- frontend/src/routes/(app)/files/+page.svelte
- frontend/src/routes/(app)/statistics/+page.svelte
> Refactor UI clean up

- backend/src/main/java/ch/nova_omnia/lernello/service/ProgressService.java
- backend/src/main/java/ch/nova_omnia/lernello/service/block/AIBlockService.java
- backend/src/main/java/ch/nova_omnia/lernello/service/block/AIPromptTemplate.java
> add question validation with ai

- frontend/src/lib/components/blocks/BlockOverviewItem.svelte
- frontend/src/lib/components/dialogs/GenerateTheoryModal.svelte
> fix: lining

- backend/.env.example
- frontend/.env.example
- node_modules/.package-lock.json
- Moves example env to BE where it is supposed to be.
- remove unintended lock file
> chore: update .env.example files and remove package-lock.json

- documentation/TranslatedBlock.drawio
> _upload class diagram._
---
> _._
> uploaded class diagram

- backend/build.gradle.kts
- backend/src/main/java/ch/nova_omnia/lernello/api/LearningKitRestController.java
- backend/src/main/java/ch/nova_omnia/lernello/service/EmailService.java
- backend/src/main/java/ch/nova_omnia/lernello/service/LearningKitService.java
- backend/src/test/java/ch/nova_omnia/lernello/JacksonConfigTests.java
- backend/src/test/java/ch/nova_omnia/lernello/service/CustomUserDetailsServiceTest.java
- backend/src/test/java/ch/nova_omnia/lernello/service/EmailServiceTest.java
- backend/src/test/java/ch/nova_omnia/lernello/service/FileSystemServiceTest.java
- backend/src/test/java/ch/nova_omnia/lernello/service/LearningKitServiceTest.java
- backend/src/test/java/ch/nova_omnia/lernello/service/ProgressServiceTest.java
- backend/src/test/java/ch/nova_omnia/lernello/service/UserServiceTest.java
- backend/src/test/java/ch/nova_omnia/lernello/service/test/EmailServiceTest.java
- backend/src/test/java/ch/nova_omnia/lernello/service/test/FileSystemServiceTest.java
> Added tests for Service classes
---
> _Not 100% of methods tested because not feasable or logical for unittests
> 478 expand test coverage

- frontend/src/lib/components/learningkit/LearningKitItem.svelte
- frontend/src/lib/i18n/locales/en.json
- frontend/src/routes/(app)/dashboard/+page.svelte
- frontend/src/routes/(app)/learningkit/[learningKitId]/edit-form/+page.server.ts
- frontend/src/routes/(app)/learningkits/+page.svelte
> add disabled state from deadline date

- backend/src/main/java/ch/nova_omnia/lernello/repository/BlockProgressRepository.java
- backend/src/main/java/ch/nova_omnia/lernello/service/BlockService.java
- backend/src/main/java/ch/nova_omnia/lernello/service/LearningUnitService.java
- backend/src/main/java/ch/nova_omnia/lernello/service/ProgressService.java
- backend/src/test/java/ch/nova_omnia/lernello/service/LearningUnitServiceTest.java
> 472 fix answer validation

- frontend/src/routes/(app)/learningunit/[learningUnitId]/+page.svelte
> fix: sidebar

- frontend/src/routes/(app)/learningkit/[learningKitId]/+page.svelte
> refactor: update delete confirmation text to use localized string
